name: Twoslash Code Sample Repros

on:
  push:
    branches:
      - orta-twoslash-repros
  schedule:
    - cron:  '0 8 * * *'
  repository_dispatch:
    types: run-twoslash-repros
  issues:
    types:
      - labeled
  workflow_dispatch: {}

jobs:
  run:
    if: ${{ !github.event.label }}
    runs-on: ubuntu-latest
    steps:
    - name: Use node
      uses: actions/setup-node@v1
    - uses: microsoft/TypeScript-Twoslash-Repro-Action@master
      with: 
        github-token: ${{ secrets.TS_BOT_GITHUB_TOKEN }}
  
  bisect:
    if: ${{ github.event.label.name == 'Bisect Repro' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v1
      with:
        node-version: 16
    - uses: microsoft/TypeScript-Twoslash-Repro-Action@master
      with: 
        github-token: ${{ secrets.TS_BOT_GITHUB_TOKEN }}
        bisect: ${{ github.event.issue.number }}
